<?php $title = 'categories'; ?>
<!-- demarre une tamporisation de sortie -->
<?php ob_start(); ?>
<section class='sectionUniversel'>
    <h2>Category : <?= htmlspecialchars(htmlentities($categories['0']['name'])) ?></h2>
    
    <div class='divCategory'>
        <?php foreach($categories as $value): ?> 
            <a href="index.php?action=oneCar&id=<?= htmlspecialchars(htmlentities($value['id'])) ?>">
                <img src="www/imgBoerbullMotors/<?= htmlspecialchars(htmlentities($value['image_url'])) ?>"  height="250" width="350" alt="<?= htmlspecialchars(utf8_encode($value['modele'])) ?>">
                <p><?= htmlspecialchars(htmlentities($value['marque'])) . ' ' . htmlspecialchars(utf8_encode($value['modele'])) ?></p>
            </a>   
        <?php endforeach ?>  
        <?php //pre_var_dump($current_page, null, true); ?>
    </div>
    
    <!-- pagination -->
    <div>
        <span style="display: <?= ($current_page === 1) ? 'none' : '' ?>">
            <a href="index.php?action=category&id_category=<?= $_GET['id_category'] ?>&page=<?= $current_page - 1 ?>" > << Précédente</a>
        </span>
    
        <?php for ($page=1; $page <= $nb_pages ; $page++) : ?>
            <span <?= ($current_page === $page) ? 'active' : '' ?> >
                <a href="index.php?action=category&id_category=<?= $_GET['id_category'] ?>&page=<?= $page ?>" ><?= $page ?></a>
            </span>
        <?php endfor ?>
    
        <span style="display:<?= ($current_page === $nb_pages) ? 'none' : '' ?>">
            <a href="index.php?action=category&id_category=<?= $_GET['id_category'] ?>&page=<?= $current_page + 1 ?>" >Suivante >> </a>
        </span>
    </div>
</section>
<!-- fermer la tamporisation de sortie et le mettre dans une variable -->
<?php $content = ob_get_clean(); ?>
<?php require_once 'www/layout/layoutView.phtml'; ?>